# Generated by Django 5.1.1 on 2024-10-04 11:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiProducts', '0002_alter_products_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Descripción',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='products',
            name='Nombre',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
